import type { User, Expense } from './types';
export const MOCK_USERS: User[] = [
  { id: 'user-1', name: 'Alice Johnson', email: 'alice@clarity.com', role: 'employee' },
  { id: 'user-2', name: 'Bob Williams', email: 'bob@clarity.com', role: 'employee' },
  { id: 'user-3', name: 'Charlie Brown', email: 'charlie@clarity.com', role: 'manager' },
  { id: 'user-4', name: 'Diana Prince', email: 'diana@clarity.com', role: 'admin' },
];
export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    userId: 'user-1',
    merchant: 'Cloudflare Cafe',
    amount: 12.50,
    currency: 'USD',
    date: new Date('2024-07-20T12:30:00Z').getTime(),
    description: 'Team lunch',
    status: 'pending',
    category: 'Meals',
    history: [],
  },
  {
    id: 'exp-2',
    userId: 'user-2',
    merchant: 'Stripe',
    amount: 99.00,
    currency: 'USD',
    date: new Date('2024-07-19T10:00:00Z').getTime(),
    description: 'Software subscription for project',
    status: 'pending',
    category: 'Software',
    history: [],
  },
  {
    id: 'exp-3',
    userId: 'user-1',
    merchant: 'United Airlines',
    amount: 450.00,
    currency: 'USD',
    date: new Date('2024-07-15T08:45:00Z').getTime(),
    description: 'Flight to customer meeting in SFO',
    status: 'approved',
    category: 'Travel',
    history: [
      {
        approverId: 'user-3',
        approverName: 'Charlie Brown',
        status: 'approved',
        timestamp: new Date('2024-07-16T14:00:00Z').getTime(),
        notes: 'Approved.',
      },
    ],
  },
  {
    id: 'exp-4',
    userId: 'user-2',
    merchant: 'Amazon Web Services',
    amount: 1200.00,
    currency: 'USD',
    date: new Date('2024-07-01T00:00:00Z').getTime(),
    description: 'Monthly server costs',
    status: 'approved',
    category: 'Utilities',
    history: [
      {
        approverId: 'user-3',
        approverName: 'Charlie Brown',
        status: 'approved',
        timestamp: new Date('2024-07-02T11:00:00Z').getTime(),
      },
    ],
  },
  {
    id: 'exp-5',
    userId: 'user-1',
    merchant: 'Office Depot',
    amount: 75.20,
    currency: 'USD',
    date: new Date('2024-07-18T16:20:00Z').getTime(),
    description: 'Stationery and office supplies',
    status: 'rejected',
    category: 'Office Supplies',
    history: [
      {
        approverId: 'user-3',
        approverName: 'Charlie Brown',
        status: 'rejected',
        timestamp: new Date('2024-07-19T09:30:00Z').getTime(),
        notes: 'Please use the company account for supplies.',
      },
    ],
  },
];